# ===========================================
# Information Settings
# ===========================================

#navigation
menu:
  article: /
  archives: /archives
  tags: /tags
  about: /about
  # RSS: /atom.xml

# favicon
favicon:

# ===========================================
# Color&Schemes Setting
# ===========================================

## Common

# Navigator Language
local-nav: false

# Mobile-Header
# light | dark
mobile-header: light

# Scheme
# banderole | balance
scheme: banderole

# Header Style
# line | block
header-style: block

# theme-style
# default: dark | green | blue | purple
# miku | sakura | snowmiku
theme-style: custom

# ===========================================
# Article Setting
# ===========================================

# Navigator in post
toc: true

# Use copyright infomation
copyright:
  enable: false
  # license:

#Reword button or message(fill your QRCode of any Pay.)
reward:
  enable: false
  # message:
  qrcode:
    # alipay:
    #   url:
    #   message:
    # wechat:
    #   url:
    #   message:
    # paypal:
    #   url:
    #   message:

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments:
  enable: false

  # disqus:
  # livere_datauid:

  # changyan:
  #   appid:
  #   appkey:

  # gitalk:
  #   owner:
  #   repo:
  #   client_id:
  #   client_secret:
  #   admin:

# sub //Please just fill out ID.
sub:
  twitter: nzws_me
  github: yuzulabo
  mastodon: https://don.nzws.me/@nzws

#Friend link
# friendLink:

# ===========================================
# Analytics
# ===========================================

analytics:
  google: UA-144848121-1
  baidu:

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: false

# ===========================================
# Theme Settings
# ===========================================

# pjax
pjax: false

# mathjax
mathjax: false

# lightbox
lightbox: true

# lazyload
lazyload: false

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# Created Time
since: 2019

# plugin
# plugins:

# about
# self:

# ===========================================
# Search Settings
# ===========================================

# Search
search:
  enable: false
  label: 搜索一下？

# ===========================================
# Documents Styles
# ===========================================

# article-fonts
# default | Simsun | YaHei | Hel | Custom
fonts-style: Custom

# code-fonts
# default | Custom
code-style: default

# ===========================================
# WebApp Settings (iOS)
# ===========================================


# ===========================================
# Version
# ===========================================
version: 3.0

#theme_author: Co1MugX
